name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test
      - run: curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI: true
